# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers

    role_hierarchy:
        ROLE_GESTIONNAIRE: [ROLE_USER]
        ROLE_ADMIN:       [ROLE_GESTIONNAIRE]


    providers:
        in_memory:
            memory:
                users:
                  admin: { password: 25e4ee4e9229397b6b17776bfceaf8e7, roles: 'ROLE_ADMIN' } #adminpass
                  gestionnaire: { password: 1a1dc91c907325c69271ddf0c944bc72, roles: 'ROLE_GESTIONNAIRE'}  #pass
                  user: { password: 1a1dc91c907325c69271ddf0c944bc72, roles: 'ROLE_USER'}  #pass
 
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic: ~
            #form_login:
             #   login_path:  /login
             #   check_path:  /login_check
        main:
            anonymous: ~
            # activate different ways to authenticate
    access_control:
        - { path: ^/admin, roles: ROLE_GESTIONNAIRE }
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: md5
            encode_as_base64: false
            iterations: 0
